### ISSUE TITLE
Expired token while upload 10x dataset's 16,377 files

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/upload-service#114]
<img width="1213" alt="screen shot 2018-07-11 at 1 46 29 pm" src="https://user-images.githubusercontent.com/19597324/42599329-c1be282a-8513-11e8-86da-4447d0d7af7a.png">

The above error appreared while trying to upload the 10x dataset

**Comment by sampierson** [comment]
@willrockout I assume this is staging?  What version of the `hca` program (run `hca --version`)?

**Comment by sampierson** [comment]
@parthshahva I remember adding code to catch TokenExpired errors and retry, but I don't see it now!  Let me go search my git repo.

I also have a concern about compound boto3 S3Transfer commands.  boto3 is not going to retry if it gets a TokenExpired 99% of the way through a gigabyte multipart upload.  Catching it at a higher level, getting a new token and retrying would cause us to re-upload the 99%.  Perhaps we should refresh the token every time before an upload, or before a large upload.

**Comment by sampierson** [comment]
@willrockout I have deployed a hotfix to staging to ease this problem a little.  1 hour access tokens are now issued instead of 15 minutes.  This means that it is less likely your token is going to expire in the middle of an upload.

If you are going to upload a crap-ton of files, do 2 things:
1. partition the files so each upload command takes less than an hour
2. before you start, delete the credentials for this upload area out of `~/.config/hca/config.json`.  This will mean you get a fresh full 1 hour at the start of the upload run.

p.s. if you use Vim, you might find this command useful to make your config.json more readable while editing: `:1,$!jq .`

**Comment by MDunitz** [comment]
I ran into this issue while trying to test the prevalidation size check for a 1TB file in dev. According to the command line logging it was only 7% uploaded when it failed.

**Comment by sampierson** [comment]
See description of problem and discussion of solutions in "Part II" of this doc: https://docs.google.com/document/d/1JFO75A9OR1gnCT1nYHH5p-vEaf0-TdOtOme3M3b9g3A/edit#
