### ISSUE TITLE
Upload report

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/upload-service#38]
Generate upload report detailing files uploaded and their checksums (suitable for inclusion in metadata?)

Maybe this is just a different version of `upload list`.  After all I'm less interested in what I just uploaded than then entire contents of the upload area.

Let's ask @malloryfreeberg what would be ideal.

**Comment by malloryfreeberg** [comment]
(If this is just about uploading *files*, and not *metadata*) as a user uploading my data files to my submission, I would want to know:
1. Whether the submission is waiting for additional files and what those files are*
1. What the checksums are for each file so I can check the fidelity of the upload
1. The validation state of my files (e.g. 100 valid, 1 invalid, 5 validating) so I know roughly where I'm at in the validation stage

*This is important for cases where e.g. there are filename mismatches between the metadata spreadsheet (what the upload area is expecting) and what I'm actually uploading. This information might be difficult/impossible to get because it involves querying for files in the metadata that don't have a cloudURL assigned yet.

Might have more ideas later :)

**Comment by sampierson** [comment]
I like it!  We should get the CLI to interface with Ingest to figure out which files still need to be uploaded.  This is kind of like "automatic mode" where you just start the tool and let it figure out what to do.

**Comment by parthshahva** [comment]
@parthshahva to interface with Purple to add to their report
